// Objects365 class names
export const OBJ365_CLASSES = [
  'Person',
  'Sneakers',
  'Chair',
  'Other Shoes',
  'Hat',
  'Car',
  'Lamp',
  'Glasses',
  'Bottle',
  'Desk',
  'Cup',
  'Street Lights',
  'Cabinet/shelf',
  'Handbag/satchel',
  'Bracelet',
  'Plate',
  'Picture/Frame',
  'Helmet',
  'Book',
  'Gloves',
  'Storage box',
  'Boat',
  'Leather Shoes',
  'Flower',
  'Bench',
  'Potted Plant',
  'Bowl/Basin',
  'Trash bin Can',
  'Slippers',
  'Bowl',
  'Flag',
  'Pillow',
  'Boots',
  'Vase',
  'Microphone',
  'Necklace',
  'Ring',
  'SUV',
  'Wine Glass',
  'Camera',
  'Candle',
  'Backpack',
  'Wine Bottle',
  'Laptop',
  'Towel',
  'Stuffed Toy',
  'Paddle',
  'Bed',
  'Guitar',
  'Spoon',
  'Clock',
  'Fork',
  'Carpet',
  'Scissors',
  'Sofa',
  'Toy',
  'Stroller',
  'Ballon',
  'Tape',
  'Coffee Table',
  'Knives',
  'Wine Glasses',
  'Boat/ship',
  'Basketball',
  'Picture',
  'Bicycle',
  'Bottle',
  'Microphone',
  'Tennis Racket',
  'Stool',
  'Head Phone',
  'Board Eraser',
  'Marker',
  'Power outlet',
  'Lamp',
  'Fire Extinguisher',
  'Power Strip',
  'Fan',
  'White Board',
  'Ball',
  'Pencil',
  'Wall Clock',
  'Hammer',
  'Router/modem',
  'Projector',
  'Globe',
  'Umbrella',
  'Hanger',
  'Knife',
  'Piano',
  'Gas Stove',
  'Cups',
  'Cutting/chopping Board',
  'Coffee Machine',
  'Weighing Scale',
  'Microwave',
  'Kitchen & dining room table',
  'Rice Cooker',
  'Coffee cup',
  'Clothes Dryer',
  'Toilet',
  'Indexing Mannequin',
  'Wardrobe',
  'Mirror',
  'Teapot',
  'Cabbage',
  'Radio',
  'Printer',
  'Air Conditioner',
  'Tissue Paper',
  'Refrigerator',
  'Washing Machine/Drying Machine',
  'Couch',
  'Picture/painting',
  'Car',
  'Desk',
  'TV',
  // ... truncated list for brevity. Objects365 has 365 classes; for our use we only need indices mapping.
];
